server:
  port: 81

dubbo:
  application:
    name: consumer
    qos-enable: false
  registry:
    address: zookeeper://192.168.16.100:2181
  consumer:
    cache: false
    check: false
    timeout: 60000
  protocol:
    name: dubbo
    port: '20881'

  scan:
    base-packages: com.jcs.consumer

spring:
  datasource:
    url: jdbc:mysql://rm-wz9nfy4so0rvmzoo2so.mysql.rds.aliyuncs.com:3306/dota?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: test1
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
