server:
  port: 80

dubbo:
  application:
    name: api
    qos-enable: false
  registry:
    address: zookeeper://192.168.16.100:2181
  consumer:
    cache: false
    check: false
    timeout: 60000




  scan:
    base-packages: com.jcs.api