server:
  port: 83

dubbo:
  application:
    name: open-dota
    qos-enable: false
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    cache: "false"
    check: "false"
    timeout: 60000
    filter: dubboLogFilter
  provider:
    cache: "false"
    check: "false"
    timeout: 60000
    filter: dubboLogFilter
  monitor:
    protocol: register
  protocol:
    name: dubbo
    port: "20883"
  scan:
    base-packages: com.jcs.opendota

spring:
  datasource:
    url: jdbc:mysql://rm-wz9nfy4so0rvmzoo2so.mysql.rds.aliyuncs.com:3306/dota?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: test1
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  #实体类所做包
#  type-aliases-package: learning.model
  #mapper.xml所在位置
  mapper-locations: classpath:mappers/*.xml